name: Angular + Cordova Test 
# Controls when the action will run and triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  
  schedule:
    - cron:  '1 22 * * *'

jobs:
  # This will build an IPA & Upload the artifact in iOS.zip

  # 
  build-ios-dev-test:
    runs-on: ubuntu-latest
    steps:
      - name: Angular Cordova Dev iOS
        uses: ionic-team/appflow-build@v1
        with:
          token: ${{ secrets.SECRET }}
          app-id: 02fa9974
          platform: iOS
          build-type: development
          certificate: ios_dev
          native-config: ios_dev
          upload-artifact: ios-dev
          artifact-retention-days: 1

      - name: Report Status
        if: always()
        uses: likhith99/notify-slack-action@master
        with:
          status: ${{ job.status }}
          notify_when: 'failure'
#         env:
#           SLACK_WEBHOOK_URL: ${{ secrets.ACTION_MONITORING_SLACK }}
          
    # 
  build-web-test:
    runs-on: ubuntu-latest
    steps:
      - name: Angular Cordova web test 
        uses: ionic-team/appflow-build@v1
        with:
          token: ${{ secrets.SECRET }}
          app-id: 02fa9974
          platform: Web
          artifact-retention-days: 1

      - name: Report Status
        if: always()
        uses: likhith99/notify-slack-action@master
        with:
          status: ${{ job.status }}
          notify_when: 'failure'
#         env:
#           SLACK_WEBHOOK_URL: ${{ secrets.ACTION_MONITORING_SLACK }}    


  build-ios-appstore-test:
    runs-on: ubuntu-latest
    steps:
      - name: Angular Cordova Appstore iOS
        uses: ionic-team/appflow-build@v1
        with:
          token: ${{ secrets.SECRET }}
          app-id: 02fa9974
          platform: iOS
          build-type: app-store
          certificate: ios_prod
          native-config: ios_prod
          upload-artifact: ios-prod
          artifact-retention-days: 1

      - name: Report Status
        if: always()
        uses: likhith99/notify-slack-action@master
        with:
          status: ${{ job.status }}
          notify_when: 'failure'
#         env:
#           SLACK_WEBHOOK_URL: ${{ secrets.ACTION_MONITORING_SLACK }}
          
          
          
  build-ios-enterprise-test:
    runs-on: ubuntu-latest
    steps:
      - name: Angular Cordova Appstore iOS
        uses: ionic-team/appflow-build@v1
        with:
          token: ${{ secrets.SECRET }}
          app-id: 02fa9974
          platform: iOS
          build-type: enterprise
          certificate: enterprise
          native-config: ios_ent
          upload-artifact: ios-ent
          artifact-retention-days: 1

      - name: Report Status
        if: always()
        uses: likhith99/notify-slack-action@master
        with:
          status: ${{ job.status }}
          notify_when: 'failure'
#         env:
#           SLACK_WEBHOOK_URL: ${{ secrets.ACTION_MONITORING_SLACK }}
          
          
  build-android-debug-test:
    runs-on: ubuntu-latest
    steps:
      - name: Angular Cordova Appstore iOS
        uses: ionic-team/appflow-build@v1
        with:
          token: ${{ secrets.SECRET }}
          app-id: 02fa9974
          platform: Android
          build-type: debug
          upload-artifact: android-debug
          artifact-retention-days: 1

      - name: Report Status
        if: always()
        uses: likhith99/notify-slack-action@master
        with:
          status: ${{ job.status }}
          notify_when: 'failure'
#         env:
#           SLACK_WEBHOOK_URL: ${{ secrets.ACTION_MONITORING_SLACK }}
          
          
          
  build-android-release-test:
    runs-on: ubuntu-latest
    steps:
      - name: Angular Cordova Appstore iOS
        uses: ionic-team/appflow-build@v1
        with:
          token: ${{ secrets.SECRET }}
          app-id: 02fa9974
          platform: Android
          build-type: release
          certificate: prod
          upload-artifact: android
          artifact-retention-days: 1

      - name: Report Status
        if: always()
        uses: likhith99/notify-slack-action@master
        with:
          status: ${{ job.status }}
          notify_when: 'failure'
#         env:
#           SLACK_WEBHOOK_URL: ${{ secrets.ACTION_MONITORING_SLACK }}
